### ISSUE TITLE
View function did not return a response

### ISSUE THREAD

**Issue by glutamate** [BeautifulDestinations/python-rest-wrapper#2]
Prediction crashes with error "View function did not return a response".

Log file (/var/log/upstart/pypredict.log on server)

```
90.207.130.65 - - [06/Jan/2016 06:41:04] "POST /api/v1/predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

To reproduce:
1. pull latest insert_aesthetic_prediction branch
2. `google-chrome test.html`
3. Upload an image

**Comment by PGrothaus** [comment]
Prediction throws an exception:

`Exception: tostring() has been removed. Please call tobytes() instead.`

Will take care of it. Looks like different version of PIL on the server and local machine.

**Comment by glutamate** [comment]
Ok. I have set up the server as a service under upstart, so it comes up on boot and restarts if it crashes (and the output goes to the logfile).

To restart when you change the code or installed packages, just run

```
restart pypredict
```

as root

**Comment by PGrothaus** [comment]
restart pypredict doesn't work for me. I get

restart: Unknown instance:

**Comment by glutamate** [comment]
Thats because there is an error in the python code

root@image-prediction:~/python-rest-wrapper# python rest-server.py
Traceback (most recent call last):
  File "rest-server.py", line 25, in <module>
    import deployed_model
  File "/root/theano_playground/deployed_model.py", line 51
    if ( len( np.shape( pred ) ) > 1 ):
     ^
IndentationError: expected an indented block

On Wed, Jan 6, 2016 at 2:01 PM, Philipp Grothaus notifications@github.com
wrote:

> restart pypredict doesn't work for me. I get
> 
> restart: Unknown instance:
> 
> On Wed, Jan 6, 2016 at 12:24 PM, Tom Nielsen notifications@github.com
> wrote:
> 
> > Ok. I have set up the server as a service under upstart, so it comes up
> > on
> > boot and restarts if it crashes (and the output goes to the logfile).
> > 
> > To restart when you change the code or installed packages, just run
> > 
> > restart pypredict
> > 
> > as root
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169311992
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169330075
> .

## 

*Tom Nielsen | Chief Data Science Officer *
Soho works | Tea building | 56 Shoreditch High St | London E1 6JJ
+44 7961 270 416

_Beautiful Destinations | The world’s largest travel influencer on
Instagram_
Destinations https://instagram.com/beautifuldestinations/ | Hotels
https://instagram.com/beautifulhotels | Cuisines
https://instagram.com/beautifulcuisines | Matters
https://instagram.com/beautifulmatters
www.beautifuldestinations.com

**Comment by glutamate** [comment]
I have disables the upstart service so you can just go on and run python
rest-server.py till it works

On Wed, Jan 6, 2016 at 2:05 PM, Tom Nielsen tomn@beautifuldestinations.com
wrote:

> Thats because there is an error in the python code
> 
> root@image-prediction:~/python-rest-wrapper# python rest-server.py
> Traceback (most recent call last):
>   File "rest-server.py", line 25, in <module>
>     import deployed_model
>   File "/root/theano_playground/deployed_model.py", line 51
>     if ( len( np.shape( pred ) ) > 1 ):
>      ^
> IndentationError: expected an indented block
> 
> On Wed, Jan 6, 2016 at 2:01 PM, Philipp Grothaus <notifications@github.com
> 
> > wrote:
> > 
> > restart pypredict doesn't work for me. I get
> > 
> > restart: Unknown instance:
> > 
> > On Wed, Jan 6, 2016 at 12:24 PM, Tom Nielsen notifications@github.com
> > wrote:
> > 
> > > Ok. I have set up the server as a service under upstart, so it comes up
> > > on
> > > boot and restarts if it crashes (and the output goes to the logfile).
> > > 
> > > To restart when you change the code or installed packages, just run
> > > 
> > > restart pypredict
> > > 
> > > as root
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169311992
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169330075
> > .
> 
> ## 
> 
> *Tom Nielsen | Chief Data Science Officer *
> Soho works | Tea building | 56 Shoreditch High St | London E1 6JJ
> +44 7961 270 416
> 
> _Beautiful Destinations | The world’s largest travel influencer on
> Instagram_
> Destinations https://instagram.com/beautifuldestinations/ | Hotels
> https://instagram.com/beautifulhotels | Cuisines
> https://instagram.com/beautifulcuisines | Matters
> https://instagram.com/beautifulmatters
> www.beautifuldestinations.com

## 

*Tom Nielsen | Chief Data Science Officer *
Soho works | Tea building | 56 Shoreditch High St | London E1 6JJ
+44 7961 270 416

_Beautiful Destinations | The world’s largest travel influencer on
Instagram_
Destinations https://instagram.com/beautifuldestinations/ | Hotels
https://instagram.com/beautifulhotels | Cuisines
https://instagram.com/beautifulcuisines | Matters
https://instagram.com/beautifulmatters
www.beautifuldestinations.com

**Comment by PGrothaus** [comment]
Predictions work now, but much slower than the last time we tried it. I remember it to be instantaneous

**Comment by glutamate** [comment]
ok. We can look at that later. That's not important right now.

On Wed, Jan 6, 2016 at 2:28 PM, Philipp Grothaus notifications@github.com
wrote:

> Predictions work now, but much sower than the last time we tried it. I
> remember it to be instantaneous
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169336190
> .

## 

*Tom Nielsen | Chief Data Science Officer *
Soho works | Tea building | 56 Shoreditch High St | London E1 6JJ
+44 7961 270 416

_Beautiful Destinations | The world’s largest travel influencer on
Instagram_
Destinations https://instagram.com/beautifuldestinations/ | Hotels
https://instagram.com/beautifulhotels | Cuisines
https://instagram.com/beautifulcuisines | Matters
https://instagram.com/beautifulmatters
www.beautifuldestinations.com

**Comment by PGrothaus** [comment]
About 8 times slower than on my local machine

**Comment by glutamate** [comment]
But is that the difference btw GPU and CPU?

Tom

On Wed, Jan 6, 2016 at 2:38 PM, Philipp Grothaus notifications@github.com
wrote:

> About 8 times slower than on my local machine
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169339365
> .

## 

*Tom Nielsen | Chief Data Science Officer *
Soho works | Tea building | 56 Shoreditch High St | London E1 6JJ
+44 7961 270 416

_Beautiful Destinations | The world’s largest travel influencer on
Instagram_
Destinations https://instagram.com/beautifuldestinations/ | Hotels
https://instagram.com/beautifulhotels | Cuisines
https://instagram.com/beautifulcuisines | Matters
https://instagram.com/beautifulmatters
www.beautifuldestinations.com

**Comment by PGrothaus** [comment]
local machine:
GPU 0.035 sec
CPU: 1.49 sec

server:
CPU: 12.47 sec

**Comment by glutamate** [comment]
did you do the float32 thing?

On Wed, Jan 6, 2016 at 2:42 PM, Philipp Grothaus notifications@github.com
wrote:

> local machine:
> GPU 0.035 sec
> CPU: 1.49 sec
> 
> server:
> CPU: 12.47 sec
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BeautifulDestinations/python-rest-wrapper/issues/2#issuecomment-169340674
> .

## 

*Tom Nielsen | Chief Data Science Officer *
Soho works | Tea building | 56 Shoreditch High St | London E1 6JJ
+44 7961 270 416

_Beautiful Destinations | The world’s largest travel influencer on
Instagram_
Destinations https://instagram.com/beautifuldestinations/ | Hotels
https://instagram.com/beautifulhotels | Cuisines
https://instagram.com/beautifulcuisines | Matters
https://instagram.com/beautifulmatters
www.beautifuldestinations.com

**Comment by PGrothaus** [comment]
Yes.

**Comment by glutamate** [comment]
I still get this error

```
ValueError: View function did not return a response
90.207.130.65 - - [06/Jan/2016 09:51:51] "POST /api/v1/predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

Are you testing through the test.html file in chrome, and what image are you using (please attach/email)

**Comment by PGrothaus** [comment]
I use the test.html file. I use the attached image. The ouput is:

{
  "name": "uploads/381642261427008739_276192188.jpg",
  "this": {
    "prediction": "[0.021789569]",
    "time to predict": "12.6438498497"
  }
}

**Comment by glutamate** [comment]
attached image dont work in github issues, can you email directly please

**Comment by glutamate** [comment]
ok, never mind. I got it to work on an IG image
